spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatinterface
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/chat-app/protocol/openid-connect/certs

llm:
  provider: mistral

ollama:
  base-url: http://localhost:11434

mistral:
  api-key: 5Lg5SQ8kolwnjxmJvU3YxiQwex3fpQzc
  model: mistral-small-latest

context-engine:
  base-url: http://localhost:8082
